// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzLUHa-EHLUJS4dQIaEPnnYIW5g6XdnHY',
    appId: '1:883565727878:web:2604c25b6d850abdd98107',
    messagingSenderId: '883565727878',
    projectId: 'scanserve-app-1010',
    authDomain: 'scanserve-app-1010.firebaseapp.com',
    storageBucket: 'scanserve-app-1010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3W9958SDqpNxECn_dfDd8rIM_NkzP3aY',
    appId: '1:883565727878:android:dafbd542cae90758d98107',
    messagingSenderId: '883565727878',
    projectId: 'scanserve-app-1010',
    storageBucket: 'scanserve-app-1010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxSfp5L68vhuIxYtR0XMpcpV2sFvqU60k',
    appId: '1:883565727878:ios:9c2782e49cd60fe2d98107',
    messagingSenderId: '883565727878',
    projectId: 'scanserve-app-1010',
    storageBucket: 'scanserve-app-1010.firebasestorage.app',
    iosBundleId: 'com.trl.startupLaunch',
  );
}
